Repository lolWK/ddingddong-game, pull requests merged in 2023-05, with the labels that each got.

#3 chore: 초기 설정 세팅
  .eslintrc.js
  .gitignore
  .prettierrc
  package-lock.json
  package.json
Labels: setting

#5 chore: firebase 세팅
  firebase.js
  index.html
  index.js
  package-lock.json
  package.json
Labels: setting

#12 chore: firebase 배포
  .eslintrc.js
  .firebase/hosting.YnVpbGQ.cache
  .firebaserc
  .prettierignore
  build/404.html
  build/firebaseConfig.js
  build/index.html
  build/index.js
  build/style.css
  firebase.js
  firebase.json
  index.js
  package-lock.json
  package.json
Labels: setting

#13 chore: 폴더 및 파일 생성
  build/index.html
  build/src/css/style.css
  build/src/images/arrow.png
  build/src/images/characters.png
  build/src/images/coin-shadow.png
  build/src/images/coin.png
  build/src/images/map.png
  build/src/images/shadow.png
  build/src/js/firebaseConfig.js
  build/src/js/index.js
Labels: setting

#14 docs: README 작성
  README.md
Labels: docs

#16 fix: firebase 환경 변수 문제 해결
  .gitignore
  build/index.html
  build/src/js/firebase/firebase.js
  build/src/js/firebaseConfig.js
  package-lock.json
  package.json
Labels: bug

#23 feat: 사용할 헬퍼 함수들 추가
  build/src/js/game/helper.js
Labels: feat

#22 feat: 라이브러리 연동
  .firebase/hosting.YnVpbGQ.cache
  .gitignore
  build/index.html
  build/src/css/style.css
  build/src/js/ml5.js
Labels: feat

#32 feat: 간식 코인 생성 기능
  build/src/css/style.css
  build/src/js/game/coin.js
  build/src/js/game/initGame.js
  build/src/js/game/store.js
Labels: feat

#36 feat: 시작 버튼과 관련된 기능
  build/index.html
  build/src/js/game/KeyPress.js
  build/src/js/game/coin.js
  build/src/js/game/initGame.js
  build/src/js/game/ml5.js
  build/src/js/game/timer.js
Labels: feat

#37 feat: 점수 정보 렌더링
  build/index.html
  build/src/js/game/player.js
  build/src/js/game/score.js
Labels: feat
